# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://desmondrawls.github.io
title: H.E.L.M.
subtitle: HELPING EVERYBODY LEARN MORE
author: Desmond Rawls
simple_search: http://google.com/search
description: I have found that my ignorance is a better indicator of where I am than my knowledge. For example, until my junior year of high school I couldn’t name all four members of the Beatle. For example, I always thought Roger and Ebert were two different people. For example, when I first met my girfriend’s mom she was appalled that i didn’t know who Angela Davis is. Today, if you were to ask me about any of these people I would talk about them like we were childhood friends. But my ignorance tells my story. It’s the same with learning to program. If I don’t take snapshots of my ignorance I’m afraid that the learning process will eventually cover it up so that I will forget what it felt like not to understand basic programming artifacts. That’s the main reason I have decided to dedicate this blog to a diary of things that I don’t understand about programming. Equally important, I think that learning to articulate my ignorance will help me overcome future challenges. Many times i find that explaining something I know is super easy while posing a question I might trip myself up. I want to be able to tell anyone teaching me or collaborating with me exactly what i need clarified in order to progress. Lastly if I ever want to be on the other side teaching someone else how to do this I need to be able to relate to beginners. I need to preserve my confused state in writing. Here goes.



# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false
